# Generated by Django 2.2.5 on 2019-09-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190905_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.DateField(blank=True, choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=50, verbose_name='Статус'),
        ),
    ]
