# Generated by Django 2.2.5 on 2019-09-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190909_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detailed',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Подробнее'),
        ),
    ]
