# Generated by Django 2.2.5 on 2019-09-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_task_detailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detailed',
            field=models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='Подробнее'),
        ),
    ]
